using InstanceBackupManager.Processing.Enums;
using InstanceBackupManager.Processing.Models.Backups;

namespace InstanceBackupManager.Processing.Policies;

/// <summary>
/// Centralizes creation, normalization, validation, and backward-compatible display of backup names.
/// </summary>
public static class BackupDisplayNamePolicy
{
    #region Constants

    /// <summary>
    /// Defines the maximum number of characters permitted in a persisted backup display name.
    /// </summary>
    public const int MaximumLength = 100;

    private const string ManualPrefix = "Manual backup - ";
    private const string PreRestorePrefix = "Pre-restore backup - ";
    private const string BeforeRestorePrefix = "Before restoring \u0022";
    private const string BeforeRestoreSuffix = "\u0022";

    #endregion

    #region Public Methods

    /// <summary>
    /// Creates a persisted display name, using a kind-specific timestamped name when no name is supplied.
    /// </summary>
    /// <param name="kind">The reason the backup is being created.</param>
    /// <param name="requestedDisplayName">The optional name entered by the user or generated by the calling workflow.</param>
    /// <param name="createdUtc">The UTC date and time assigned to the backup.</param>
    /// <returns>A normalized, valid display name.</returns>
    /// <exception cref="ArgumentException">Thrown when the supplied name is too long or contains control characters.</exception>
    public static string CreateDisplayName(
        BackupKind kind,
        string? requestedDisplayName,
        DateTimeOffset createdUtc
    )
    {
        if (!string.IsNullOrWhiteSpace(requestedDisplayName))
        {
            return Normalize(requestedDisplayName);
        }

        var prefix = kind == BackupKind.PreRestore
            ? PreRestorePrefix
            : ManualPrefix;

        return $"{prefix}{createdUtc.ToLocalTime():yyyy-MM-dd HH:mm:ss}";
    }

    /// <summary>
    /// Creates a generated name for the safety backup taken before a selected backup is restored.
    /// </summary>
    /// <param name="selectedBackup">The completed backup selected for restoration.</param>
    /// <returns>A valid name identifying the backup whose restoration triggered the safety backup.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="selectedBackup"/> is null.</exception>
    public static string CreatePreRestoreDisplayName(BackupDescriptor selectedBackup)
    {
        ArgumentNullException.ThrowIfNull(selectedBackup);

        var selectedDisplayName = GetDisplayName(selectedBackup.Manifest);
        var availableLength = MaximumLength - BeforeRestorePrefix.Length - BeforeRestoreSuffix.Length;

        if (selectedDisplayName.Length > availableLength)
        {
            selectedDisplayName = selectedDisplayName[..availableLength].TrimEnd();
        }

        return $"{BeforeRestorePrefix}{selectedDisplayName}{BeforeRestoreSuffix}";
    }

    /// <summary>
    /// Gets a backup's persisted display name or creates a backward-compatible name for a manifest written by an older version.
    /// </summary>
    /// <param name="manifest">The backup manifest to display.</param>
    /// <returns>The persisted or generated display name.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="manifest"/> is null.</exception>
    public static string GetDisplayName(BackupManifest manifest)
    {
        ArgumentNullException.ThrowIfNull(manifest);

        if (!string.IsNullOrWhiteSpace(manifest.DisplayName))
        {
            return manifest.DisplayName.Trim();
        }

        var prefix = manifest.Kind == BackupKind.PreRestore
            ? PreRestorePrefix
            : ManualPrefix;

        return $"{prefix}{manifest.CreatedUtc.ToLocalTime():yyyy-MM-dd HH:mm:ss}";
    }

    /// <summary>
    /// Normalizes and validates a display name before it is persisted or accepted from a stored manifest.
    /// </summary>
    /// <param name="displayName">The display name to normalize.</param>
    /// <returns>The trimmed display name.</returns>
    /// <exception cref="ArgumentException">Thrown when the name is blank, too long, or contains control characters.</exception>
    public static string Normalize(string displayName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(displayName);

        var normalizedDisplayName = displayName.Trim();

        if (normalizedDisplayName.Length > MaximumLength)
        {
            throw new ArgumentException(
                $"Backup names cannot exceed {MaximumLength} characters.",
                nameof(displayName)
            );
        }

        if (normalizedDisplayName.Any(char.IsControl))
        {
            throw new ArgumentException(
                "Backup names cannot contain line breaks or other control characters.",
                nameof(displayName)
            );
        }

        return normalizedDisplayName;
    }

    #endregion
}
